export const verbs = [
  {
    infinitive: 'rakastaa',
    english: 'to love',
    verbtype: 1,
    present: {
      minä: 'rakastan',
      sinä: 'rakastat',
      hän: 'rakastaa',
      me: 'rakastamme',
      te: 'rakastatte',
      he: 'rakastavat',
    },
    past: {
      minä: 'rakastin',
      sinä: 'rakastit',
      hän: 'rakasti',
      me: 'rakastimme',
      te: 'rakastitte',
      he: 'rakastivat',
    },
    passive: {
      present: {
        minä: 'rakastetaan',
        sinä: 'rakastetaan',
        hän: 'rakastetaan',
        me: 'rakastetaan',
        te: 'rakastetaan',
        he: 'rakastetaan',
      },
      past: {
        minä: 'rakastettiin',
        sinä: 'rakastettiin',
        hän: 'rakastettiin',
        me: 'rakastettiin',
        te: 'rakastettiin',
        he: 'rakastettiin',
      },
    },
  },
  {
    infinitive: 'syödä',
    verbtype: 2,
    english: 'to eat',
    present: {
      minä: 'syön',
      sinä: 'syöt',
      hän: 'syö',
      me: 'syömme',
      te: 'syötte',
      he: 'syövät',
    },
    past: {
      minä: 'söin',
      sinä: 'söit',
      hän: 'söi',
      me: 'söimme',
      te: 'söitte',
      he: 'söivät',
    },
    passive: {
      present: {
        minä: 'syödään',
        sinä: 'syödään',
        hän: 'syödään',
        me: 'syödään',
        te: 'syödään',
        he: 'syödään',
      },
      past: {
        minä: 'syötiin',
        sinä: 'syötiin',
        hän: 'syötiin',
        me: 'syötiin',
        te: 'syötiin',
        he: 'syötiin',
      },
    },
  },
  {
    infinitive: 'haluta',
    verbtype: 4,
    english: 'to want',
    present: {
      minä: 'haluan',
      sinä: 'haluat',
      hän: 'haluaa',
      me: 'haluamme',
      te: 'haluatte',
      he: 'haluavat',
    },
    past: {
      minä: 'halusin',
      sinä: 'halusit',
      hän: 'halusi',
      me: 'halusimme',
      te: 'halusitte',
      he: 'halusivat',
    },
    passive: {
      present: {
        minä: 'halutaan',
        sinä: 'halutaan',
        hän: 'halutaan',
        me: 'halutaan',
        te: 'halutaan',
        he: 'halutaan',
      },
      past: {
        minä: 'haluttiin',
        sinä: 'haluttiin',
        hän: 'haluttiin',
        me: 'haluttiin',
        te: 'haluttiin',
        he: 'haluttiin',
      },
    },
  },
  {
    infinitive: 'olla',
    verbtype: 4,
    english: 'to be/have',
    present: {
      minä: 'olen',
      sinä: 'olet',
      hän: 'on',
      me: 'olemme',
      te: 'olette',
      he: 'ovat',
    },
    past: {
      minä: 'olin',
      sinä: 'olit',
      hän: 'oli',
      me: 'olimme',
      te: 'olitte',
      he: 'olivat',
    },
    passive: {
      present: {
        minä: 'ollaan',
        sinä: 'ollaan',
        hän: 'ollaan',
        me: 'ollaan',
        te: 'ollaan',
        he: 'ollaan',
      },
      past: {
        minä: 'oltiin',
        sinä: 'oltiin',
        hän: 'oltiin',
        me: 'oltiin',
        te: 'oltiin',
        he: 'oltiin',
      },
    },
  },
  {
    infinitive: 'mennä',
    verbtype: 3,
    english: 'to go',
    present: {
      minä: 'menen',
      sinä: 'menet',
      hän: 'menee',
      me: 'menemme',
      te: 'menette',
      he: 'menevät',
    },
    past: {
      minä: 'menin',
      sinä: 'menit',
      hän: 'meni',
      me: 'menimme',
      te: 'menitte',
      he: 'menivät',
    },
    passive: {
      present: {
        minä: 'mennään',
        sinä: 'mennään',
        hän: 'mennään',
        me: 'mennään',
        te: 'mennään',
        he: 'mennään',
      },
      past: {
        minä: 'mentiin',
        sinä: 'mentiin',
        hän: 'mentiin',
        me: 'mentiin',
        te: 'mentiin',
        he: 'mentiin',
      },
    },
  },
  {
    infinitive: 'lukea',
    english: 'to read',
    verbtype: 1,
    present: {
      minä: 'luen',
      sinä: 'luet',
      hän: 'lukee',
      me: 'luemme',
      te: 'luette',
      he: 'lukevat',
    },
    past: {
      minä: 'luin',
      sinä: 'luet',
      hän: 'luki',
      me: 'luimme',
      te: 'luet',
      he: 'lukivat',
    },
    passive: {
      present: {
        minä: 'luetaan',
        sinä: 'luetaan',
        hän: 'luetaan',
        me: 'luetaan',
        te: 'luetaan',
        he: 'luetaan',
      },
      past: {
        minä: 'luettiin',
        sinä: 'luettiin',
        hän: 'luettiin',
        me: 'luettiin',
        te: 'luettiin',
        he: 'luettiin',
      },
    },
  },
  {
    infinitive: 'nähdä',
    verbtype: 3,
    english: 'to see',
    present: {
      minä: 'näen',
      sinä: 'näet',
      hän: 'näkee',
      me: 'näemme',
      te: 'näette',
      he: 'näkevät',
    },
    past: {
      minä: 'näin',
      sinä: 'näit',
      hän: 'näki',
      me: 'näimme',
      te: 'näitte',
      he: 'näkivät',
    },
    passive: {
      present: {
        minä: 'nähdään',
        sinä: 'nähdään',
        hän: 'nähdään',
        me: 'nähdään',
        te: 'nähdään',
        he: 'nähdään',
      },
      past: {
        minä: 'nähtiin',
        sinä: 'nähtiin',
        hän: 'nähtiin',
        me: 'nähtiin',
        te: 'nähtiin',
        he: 'nähtiin',
      },
    },
  },
  {
    infinitive: 'tulla',
    verbtype: 3,
    english: 'to come',
    present: {
      minä: 'tulen',
      sinä: 'tulet',
      hän: 'tulee',
      me: 'tulemme',
      te: 'tulette',
      he: 'tulevat',
    },
    past: {
      minä: 'tulin',
      sinä: 'tulit',
      hän: 'tuli',
      me: 'tulimme',
      te: 'tulitte',
      he: 'tulivat',
    },
    passive: {
      present: {
        minä: 'tullaan',
        sinä: 'tullaan',
        hän: 'tullaan',
        me: 'tullaan',
        te: 'tullaan',
        he: 'tullaan',
      },
      past: {
        minä: 'tultiin',
        sinä: 'tultiin',
        hän: 'tultiin',
        me: 'tultiin',
        te: 'tultiin',
        he: 'tultiin',
      },
    },
  },
  {
    infinitive: 'nukkua',
    english: 'to sleep',
    verbtype: 4,
    present: {
      minä: 'nukun',
      sinä: 'nukut',
      hän: 'nukkuu',
      me: 'nukumme',
      te: 'nukutte',
      he: 'nukkuvat',
    },
    past: {
      minä: 'nukuin',
      sinä: 'nukuit',
      hän: 'nukkui',
      me: 'nukuimme',
      te: 'nukuitte',
      he: 'nukkuivat',
    },
    passive: {
      present: {
        minä: 'nukutaan',
        sinä: 'nukutaan',
        hän: 'nukutaan',
        me: 'nukutaan',
        te: 'nukutaan',
        he: 'nukutaan',
      },
      past: {
        minä: 'nukuttiin',
        sinä: 'nukuttiin',
        hän: 'nukuttiin',
        me: 'nukuttiin',
        te: 'nukuttiin',
        he: 'nukuttiin',
      },
    },
  },
  {
    infinitive: 'juoda',
    english: 'to drink',
    verbtype: 2,
    present: {
      minä: 'juon',
      sinä: 'juot',
      hän: 'juo',
      me: 'juomme',
      te: 'juotte',
      he: 'juovat',
    },
    past: {
      minä: 'join',
      sinä: 'joit',
      hän: 'joi',
      me: 'joimme',
      te: 'joitte',
      he: 'joivat',
    },
    passive: {
      present: {
        minä: 'juodaan',
        sinä: 'juodaan',
        hän: 'juodaan',
        me: 'juodaan',
        te: 'juodaan',
        he: 'juodaan',
      },
      past: {
        minä: 'juotiin',
        sinä: 'juotiin',
        hän: 'juotiin',
        me: 'juotiin',
        te: 'juotiin',
        he: 'juotiin',
      },
    },
  },
  {
    infinitive: 'tietää',
    english: 'to know',
    verbtype: 3,
    present: {
      minä: 'tiedän',
      sinä: 'tiedät',
      hän: 'tietää',
      me: 'tiedämme',
      te: 'tiedätte',
      he: 'tietävät',
    },
    past: {
      minä: 'tiesin',
      sinä: 'tiesit',
      hän: 'tiesi',
      me: 'tiesimme',
      te: 'tiesitte',
      he: 'tiesivät',
    },
    passive: {
      present: {
        minä: 'tiedetään',
        sinä: 'tiedetään',
        hän: 'tiedetään',
        me: 'tiedetään',
        te: 'tiedetään',
        he: 'tiedetään',
      },
      past: {
        minä: 'tiedettiin',
        sinä: 'tiedettiin',
        hän: 'tiedettiin',
        me: 'tiedettiin',
        te: 'tiedettiin',
        he: 'tiedettiin',
      },
    },
  },
  {
    infinitive: 'katsoa',
    english: 'to look',
    verbtype: 1,
    present: {
      minä: 'katson',
      sinä: 'katsot',
      hän: 'katsoo',
      me: 'katsomme',
      te: 'katsotte',
      he: 'katsovat',
    },
    past: {
      minä: 'katsoin',
      sinä: 'katsoit',
      hän: 'katsoi',
      me: 'katsoimme',
      te: 'katsoitte',
      he: 'katsoivat',
    },
    passive: {
      present: {
        minä: 'katsotaan',
        sinä: 'katsotaan',
        hän: 'katsotaan',
        me: 'katsotaan',
        te: 'katsotaan',
        he: 'katsotaan',
      },
      past: {
        minä: 'katsottiin',
        sinä: 'katsottiin',
        hän: 'katsottiin',
        me: 'katsottiin',
        te: 'katsottiin',
        he: 'katsottiin',
      },
    },
  },
  {
    infinitive: 'tulla',
    english: 'to come',
    verbtype: 3,
    present: {
      minä: 'tulen',
      sinä: 'tulet',
      hän: 'tulee',
      me: 'tulemme',
      te: 'tulette',
      he: 'tulevat',
    },
    past: {
      minä: 'tulin',
      sinä: 'tulit',
      hän: 'tuli',
      me: 'tulimme',
      te: 'tulitte',
      he: 'tulivat',
    },
    passive: {
      present: {
        minä: 'tullaan',
        sinä: 'tullaan',
        hän: 'tullaan',
        me: 'tullaan',
        te: 'tullaan',
        he: 'tullaan',
      },
      past: {
        minä: 'tultiin',
        sinä: 'tultiin',
        hän: 'tultiin',
        me: 'tultiin',
        te: 'tultiin',
        he: 'tultiin',
      },
    },
  },
  {
    infinitive: 'kirjoittaa',
    english: 'to write',
    verbtype: 1,
    present: {
      minä: 'kirjoitan',
      sinä: 'kirjoitat',
      hän: 'kirjoittaa',
      me: 'kirjoitamme',
      te: 'kirjoitatte',
      he: 'kirjoittavat',
    },
    past: {
      minä: 'kirjoitin',
      sinä: 'kirjoitit',
      hän: 'kirjoitti',
      me: 'kirjoitimme',
      te: 'kirjoititte',
      he: 'kirjoittivat',
    },
    passive: {
      present: {
        minä: 'kirjoitetaan',
        sinä: 'kirjoitetaan',
        hän: 'kirjoitetaan',
        me: 'kirjoitetaan',
        te: 'kirjoitetaan',
        he: 'kirjoitetaan',
      },
      past: {
        minä: 'kirjoitettiin',
        sinä: 'kirjoitettiin',
        hän: 'kirjoitettiin',
        me: 'kirjoitettiin',
        te: 'kirjoitettiin',
        he: 'kirjoitettiin',
      },
    },
  },
  {
    infinitive: 'tehdä',
    english: 'to do',
    verbtype: 3,
    present: {
      minä: 'teen',
      sinä: 'teet',
      hän: 'tekee',
      me: 'teemme',
      te: 'teette',
      he: 'tekevät',
    },
    past: {
      minä: 'tein',
      sinä: 'teit',
      hän: 'teki',
      me: 'teimme',
      te: 'teitte',
      he: 'tekivät',
    },
    passive: {
      present: {
        minä: 'tehdään',
        sinä: 'tehdään',
        hän: 'tehdään',
        me: 'tehdään',
        te: 'tehdään',
        he: 'tehdään',
      },
      past: {
        minä: 'tehtiin',
        sinä: 'tehtiin',
        hän: 'tehtiin',
        me: 'tehtiin',
        te: 'tehtiin',
        he: 'tehtiin',
      },
    },
  },
  {
    infinitive: 'löytää',
    english: 'to find',
    verbtype: 4,
    present: {
      minä: 'löydän',
      sinä: 'löydät',
      hän: 'löytää',
      me: 'löydämme',
      te: 'löydätte',
      he: 'löytävät',
    },
    past: {
      minä: 'löysin',
      sinä: 'löysit',
      hän: 'löysi',
      me: 'löysimme',
      te: 'löysitte',
      he: 'löysivät',
    },
    passive: {
      present: {
        minä: 'löydetään',
        sinä: 'löydetään',
        hän: 'löydetään',
        me: 'löydetään',
        te: 'löydetään',
        he: 'löydetään',
      },
      past: {
        minä: 'löydettiin',
        sinä: 'löydettiin',
        hän: 'löydettiin',
        me: 'löydettiin',
        te: 'löydettiin',
        he: 'löydettiin',
      },
    },
  },
]
