import '@/styles/globals.css'

import {
  CalendarIcon,
  ChartPieIcon,
  DocumentDuplicateIcon,
  FolderIcon,
  HomeIcon,
  UsersIcon,
} from '@heroicons/react/24/outline'

import MobileSideNav from '@ui/MobileSideNav'
import DesktopSideNav from '@ui/DesktopSideNav'
import TopNav from '@ui/TopNav'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const navigation = [
  { name: 'Dashboard', href: '#', icon: HomeIcon, current: true },
  { name: 'Team', href: '#', icon: UsersIcon, current: false },
  { name: 'Projects', href: '#', icon: FolderIcon, current: false },
  { name: 'Calendar', href: '#', icon: CalendarIcon, current: false },
  { name: 'Documents', href: '#', icon: DocumentDuplicateIcon, current: false },
  { name: 'Reports', href: '#', icon: ChartPieIcon, current: false },
]
const teams = [
  { id: 1, name: 'Heroicons', href: '#', initial: 'H', current: false },
  { id: 2, name: 'Tailwind Labs', href: '#', initial: 'T', current: false },
  { id: 3, name: 'Workcation', href: '#', initial: 'W', current: false },
]
const userNavigation = [
  { name: 'Your profile', href: '#' },
  { name: 'Sign out', href: '#' },
]

export default function Layout({ children }: { children: React.ReactNode }) {
  // const [sidebarOpen, setSidebarOpen] = useState(false)
  return (
    <html lang="en" className="h-full">
      <body className={`h-full `} suppressHydrationWarning>
        <div>
          {/* Openable sidebar for mobile */}
          {/* <MobileSideNav
            sidebarOpen={sidebarOpen}
            setSidebarOpen={setSidebarOpen}
            teams={teams}
            navigation={navigation}
          /> */}

          {/* Static sidebar for desktop */}
          {/* <DesktopSideNav teams={teams} navigation={navigation} /> */}

          <div className="lg:pl-72">
            {/* <TopNav setSidebarOpen={setSidebarOpen} userNavigation={userNavigation} /> */}

            <main className="py-10">
              <div className="px-4 sm:px-6 lg:px-8">{children}</div>
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
